global.testVar = 'This is a global variable';
// global.path = 'D:/guimain-v1.2/detect_result/daily/false/';
// global.place="宁波梅山1";
global.path = 'E:/clj/new_demo/false_files/qinzhou_01/';
global.place='测试用例01';
global.errorMessage;
global.newRecord={};
global.newLine;
global.lastRecord={};
global.lastLine;
global.flag=0;
// add new global vars to maintain status
global.name='广东顺德';
global.number='05';
global.lastTrue = 0;
global.lastFalse = -1;
global.lastWarn = -1;
global.lastTrueTmp = 0;
global.lastFalseTmp = -1;
global.lastWarnTmp = -1;
global.lastBox = 0;
global.lastBoxTrue = 0;
global.lastBoxFalse = 0;
global.todayTrue = 12;
global.todayFalse = 3;
global.todayWarn = 2;
global.todayBox = 6;
global.weight = 1000;
global.updateTime = new Date().toISOString();
global.falsePath = 'E:/clj/new_demo/false_files/qinzhou_01/';
global.truePath = 'E:/clj/new_demo/false_files/true/';
global.speed2Threshold = 20;